config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments
  end

  root 'posts#index'

  namespace :admin do
    get :sign_up, to: 'users#new'
    post :sign_up, to: 'users#create'

    get :sign_in, to: 'sessions#new'
    post :sign_in, to: 'sessions#create'

    get :sign_out, to: 'sessions#destroy'

    resources :posts, except: [:show] do

      resources :comments
    end


    root to: 'posts#index'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :authenticate
  helper_method :sign_in?, :current_user

  layout "admin"

  def sign_in?
    !!session[:user_id]
  end

  def sign_in user
    session[:user_id] = user.id
  end

  def sign_out
    session[:user_id] = nil
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate
    unless sign_in?
      redirect_to admin_sign_in_path
    end
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
  layout 'layouts/admin'
  skip_before_action :authenticate

  skip_before_action do
    @post = Post.find( params[:post_id] )
  end

  def index
    @comments = @post.comments.order 
  end

  def destroy
    comment = @post.comments.find(params[:id])
    if comment.destroy
      flash[:notice] = '删除评论成功'
      redirect_to admin_post_comments_path(@post)
    else
      flash[:alert] = '删除失败'
      redirect_to admin_post_comments_path(@post)
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to admin_posts_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)
    if @post.save
      redirect_to admin_posts_path
    else
      render 'edit'
    end
  end

  def preview
    render plain: Post.render_html(post_params[:content] || "")
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private

    def post_params
      params.require(:post).permit(:title, :author, :content, :published_at)
    end

end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::BaseController
  skip_before_action :authenticate, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.where(email: params[:user][:email]).first
    if @user && @user.authenticate(params[:user][:password])
      sign_in @user
      redirect_to admin_posts_path
    else
      redirect_to admin_sign_in_path
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  skip_before_action :authenticate, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to admin_posts_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :nickname, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :format_time, :format_date


  def format_time(time)
    time.strftime("%Y-%m-%d %H:%M")
  end

  def format_date(time)
    time.strftime("%Y.%m.%d")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def index
    @post = Post.find(params[:post_id])
    res = @post.comments.collect { |comment| build_json(comment) }
  render :json => res
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter,:email, :body)
    end


  def build_json(comment)
    {
      body: comment.body,
      commenter: comment.commenter,
      'created_at' => format_time(comment.created_at)
    }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
      @post = Post.find(params[:id])
      @comments = @post.comments.order(created_at: :desc)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authenticate, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.where(email: params[:user][:email]).first
    if @user && @user.authenticate(params[:user][:password])
      sign_in @user
      redirect_to root_path
    else
      redirect_to sign_in_path
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :nickname, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

require 'redcarpet'
require 'rouge'
require 'rouge/plugins/redcarpet'

class HTML < Redcarpet::Render::HTML
  include Rouge::Plugins::Redcarpet
end

  def markdown(text)
    render_options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow' }
    }
    renderer = HTML.new(render_options)

    extensions = {
      autolink:           true,
      fenced_code_blocks: true,
      lax_spacing:        true,
      no_intra_emphasis:  true,
      strikethrough:      true,
      superscript:        true
    }
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/comments/index.html.erb
<table class="table table-striped table-hover datatable">
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Author</th>
      <th>Published at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <th><%= comment.commenter %></th>
        <td><%= comment.email %></td>
        <td><%= comment.body %></td>
        <td><%= comment.created_at %></td>
        <td>
          <%= link_to "Delete", admin_post_comment_path(@post, comment), method: 'DELETE', 'data-confirm'=> '确认删除?'%>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/posts/edit.html.erb
<div class="blog-header">
  <h1 class="blog-title">Edit a Post</h1>
</div>

<%= form_for(@post, url: admin_post_path(@post)) do |f| %>
  <div class="form-group">
    <label for="post_title">Title</label>
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="form-group">
    <label for="post_author">Author</label>
    <%= f.text_field :author, class: "form-control", placeholder: "Author" %>
  </div>
  <div class="form-group">
    <label for="post_content">Content</label>
    <%= f.text_area :content, class: "form-control wysihtml5", placeholder: "Content" %>
  </div>
  <div class="form-group">
    <label for="post_published_at">Published at</label>
    <%= f.datetime_field :published_at, class: "form-control", placeholder: "Published at" %>
  </div>
  <%= f.submit "Update", class: "btn btn-default" %>
<% end %>

app/views/admin/posts/index.html.erb
<table class="table table-striped table-hover datatable">
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Author</th>
      <th>Published at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <th><%= post.id %></th>
        <td><%= post.title %></td>
        <td><%= post.author %></td>
        <td><%= post.published_at %></td>
        <td>
          <%= link_to "Show", post_path(post) %>
          <%= link_to "Edit", edit_admin_post_path(post) %>
          <%= link_to "Delete", admin_post_path(post), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/posts/new.html.erb
<div class="blog-header">
  <h1 class="blog-title">Create a Post</h1>
</div>

<%= form_for(@post, url: admin_posts_path) do |f| %>
  <div class="form-group">
    <label for="post_title">Title</label>
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="form-group">
    <label for="post_author">Author</label>
    <%= f.text_field :author, class: "form-control", placeholder: "Author" %>
  </div>
  <div class="form-group">
    <label for="post_content">Content</label>
    <%= f.text_area :content, class: "form-control wysihtml5", placeholder: "Content" %>
  </div>
  <div class="form-group">
    <label for="post_published_at">Published at</label>
    <%= f.datetime_field :published_at, class: "form-control", placeholder: "Published at" %>
  </div>
  <%= f.submit "Create", class: "btn btn-default" %>
<% end %>

app/views/admin/posts/show.html.erb
<div class="blog-header">
  <h1 class="blog-title"><%= @post.title %></h1>
  <p class="lead blog-description"><%= @post.published_at %> by <%= @post.author %></p>
</div>

<div class="row">

  <div class="col-sm-8 blog-main">


      <div class="blog-post">

        <%= markdown(@post.content) %>

        <!--
          <ul class="nav nav-tabs">
            <li role="presentation" class="active"><a href="#">Content</a></li>
            <li role="presentation"><a href="#">Preview</a></li>
          </ul>
         -->
      </div><!-- /.blog-post -->



     <h2>Add a comment:</h2>
     <%= form_for([@post, @post.comments.build]) do |f| %>
       <p>
         <%= f.label :commenter %><br>
         <%= f.text_field :commenter %>
       </p>
       <p>
         <%= f.label :body %><br>
         <%= f.text_area :body %>
       </p>
       <p>
         <%= f.submit %>
       </p>
     <% end %>

      <h2>Comments</h2>
      <% @post.comments.each do |comment| %>
        <p>
          <strong>Commenter:</strong>
          <%= comment.commenter %>
        </p>

        <p>
          <strong>Comment:</strong>
          <%= comment.body %>
        </p>
      <% end %>

  </div><!-- /.blog-main -->



  <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">
      <h4>About</h4>
      <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
    </div>
    <div class="sidebar-module">
      <h4>Archives</h4>
      <ol class="list-unstyled">
        <li><a href="#">March 2014</a></li>
        <li><a href="#">February 2014</a></li>
        <li><a href="#">January 2014</a></li>
        <li><a href="#">December 2013</a></li>
        <li><a href="#">November 2013</a></li>
        <li><a href="#">October 2013</a></li>
        <li><a href="#">September 2013</a></li>
        <li><a href="#">August 2013</a></li>
        <li><a href="#">July 2013</a></li>
        <li><a href="#">June 2013</a></li>
        <li><a href="#">May 2013</a></li>
        <li><a href="#">April 2013</a></li>
      </ol>
    </div>
    <div class="sidebar-module">
      <h4>Elsewhere</h4>
      <ol class="list-unstyled">
        <li><a href="#">GitHub</a></li>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Facebook</a></li>
      </ol>
    </div>
  </div><!-- /.blog-sidebar -->

</div><!-- /.row -->

app/views/admin/users/new.html.erb
<div class="blog-header">
  <h1 class="blog-title">Sign Up</h1>
</div>

<%= form_for(@user, url: admin_sign_up_path) do |f| %>
  <div class="form-group">
    <label for="user_email">Email address</label>
    <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
  </div>
  <div class="form-group">
    <label for="user_nickname">Nickname</label>
    <%= f.text_field :nickname, class: "form-control", placeholder: "Nickname" %>
  </div>
  <div class="form-group">
    <label for="user_password">Password</label>
    <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
  </div>
  <div class="form-group">
    <label for="user_password_confirmation">Password confirmation</label>
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password confirmation" %>
  </div>
  <%= f.submit "Sign Up", class: "btn btn-default" %>
<% end %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Email:</strong>
  <%= comment.email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Hotson's Blog</title>

    <!-- Bootstrap core CSS -->
    <!-- <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <link href="http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
    <!-- <link href="http://getbootstrap.com/examples/blog/blog.css" rel="stylesheet"> -->

    <%= stylesheet_link_tag "application" %>

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="http://getbootstrap.com/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- <script src="http://getbootstrap.com/assets/js/ie-emulation-modes-warning.js"></script> -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= csrf_meta_tag %>
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="/admin">Posts</a>
          <a class="blog-nav-item" href="/admin/posts/new">Create a post</a>

          <% if sign_in? %>
             <%= link_to("sign out", admin_sign_out_path, class: "blog-nav-item pull-right") %>
           <% else %>
             <%= link_to("sign up", admin_sign_up_path, class: "blog-nav-item pull-right") %>
             <%= link_to("sign in", admin_sign_in_path, class: "blog-nav-item pull-right") %>

           <% end %>


        </nav>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
    <!-- <script>window.jQuery || document.write('<script src="http://getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script> -->
    <!-- <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script> -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script> -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Hotson's Blog</title>

    <!-- Bootstrap core CSS -->
    <!-- <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <link href="http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
    <!-- <link href="http://getbootstrap.com/examples/blog/blog.css" rel="stylesheet"> -->

    <%= stylesheet_link_tag "application" %>

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="http://getbootstrap.com/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- <script src="http://getbootstrap.com/assets/js/ie-emulation-modes-warning.js"></script> -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= csrf_meta_tag %>
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="/">Home</a>
          <%= link_to("sign in", admin_sign_in_path, class: "blog-nav-item pull-right") %>

        </nav>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
    <!-- <script>window.jQuery || document.write('<script src="http://getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script> -->
    <!-- <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script> -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script> -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/posts/index.html.erb
<div class="blog-header">
  <h1 class="blog-title">Hotson's Blog</h1>
  <p class="lead blog-description">Hotson's personal blog for learning Rails.</p>
</div>

<div class="row">

  <div class="col-sm-8 blog-main">

    <% @posts.each do |post| %>
      <div class="blog-post">
        <h2 class="blog-post-title"><%= link_to post.title, admin_post_path(post) %></h2>
        <p class="blog-post-meta">
          <%= post.created_at %> by <%= post.author %>

        </p>

        <%= post.content %>

      </div><!-- /.blog-post -->
    <% end %>
<!--
    <nav>
      <ul class="pager">
        <li><a href="#">Previous</a></li>
        <li><a href="#">Next</a></li>
      </ul>
    </nav>
 -->
  </div><!-- /.blog-main -->

  <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">
      <h4>About</h4>
      <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
    </div>
    <div class="sidebar-module">
      <h4>Archives</h4>
      <ol class="list-unstyled">
        <li><a href="#">March 2014</a></li>
        <li><a href="#">February 2014</a></li>
        <li><a href="#">January 2014</a></li>
        <li><a href="#">December 2013</a></li>
        <li><a href="#">November 2013</a></li>
        <li><a href="#">October 2013</a></li>
        <li><a href="#">September 2013</a></li>
        <li><a href="#">August 2013</a></li>
        <li><a href="#">July 2013</a></li>
        <li><a href="#">June 2013</a></li>
        <li><a href="#">May 2013</a></li>
        <li><a href="#">April 2013</a></li>
      </ol>
    </div>
    <div class="sidebar-module">
      <h4>Elsewhere</h4>
      <ol class="list-unstyled">
        <li><a href="#">GitHub</a></li>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Facebook</a></li>
      </ol>
    </div>
  </div><!-- /.blog-sidebar -->

</div><!-- /.row -->

app/views/posts/show.html.erb
<div class="blog-header">
  <h1 class="blog-title"><%= @post.title %></h1>
  <p class="lead blog-description"><%= @post.published_at %> by <%= @post.author %></p>
</div>

<div class="row">

  <div class="col-sm-8 blog-main">


      <div class="blog-post">

        <%= markdown(@post.content) %>

        <!--
          <ul class="nav nav-tabs">
            <li role="presentation" class="active"><a href="#">Content</a></li>
            <li role="presentation"><a href="#">Preview</a></li>
          </ul>
         -->
      </div><!-- /.blog-post -->



     <h2>Add a comment:</h2>
        <%= render 'comments/form' %>

      <h2>Comments</h2>
        <%= render @post.comments %>

  </div><!-- /.blog-main -->



  <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">
      <h4>About</h4>
      <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
    </div>
    <div class="sidebar-module">
      <h4>Archives</h4>
      <ol class="list-unstyled">
        <li><a href="#">March 2014</a></li>
        <li><a href="#">February 2014</a></li>
        <li><a href="#">January 2014</a></li>
        <li><a href="#">December 2013</a></li>
        <li><a href="#">November 2013</a></li>
        <li><a href="#">October 2013</a></li>
        <li><a href="#">September 2013</a></li>
        <li><a href="#">August 2013</a></li>
        <li><a href="#">July 2013</a></li>
        <li><a href="#">June 2013</a></li>
        <li><a href="#">May 2013</a></li>
        <li><a href="#">April 2013</a></li>
      </ol>
    </div>
    <div class="sidebar-module">
      <h4>Elsewhere</h4>
      <ol class="list-unstyled">
        <li><a href="#">GitHub</a></li>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Facebook</a></li>
      </ol>
    </div>
  </div><!-- /.blog-sidebar -->

</div><!-- /.row -->

app/views/users/new.html.erb
<div class="blog-header">
  <h1 class="blog-title">Sign Up</h1>
</div>

<%= form_for(@user, url: sign_up_path) do |f| %>
  <div class="form-group">
    <label for="user_email">Email address</label>
    <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
  </div>
  <div class="form-group">
    <label for="user_nickname">Nickname</label>
    <%= f.text_field :nickname, class: "form-control", placeholder: "Nickname" %>
  </div>
  <div class="form-group">
    <label for="user_password">Password</label>
    <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
  </div>
  <div class="form-group">
    <label for="user_password_confirmation">Password confirmation</label>
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password confirmation" %>
  </div>
  <%= f.submit "Sign Up", class: "btn btn-default" %>
<% end %>